name: "Release Domains"
description: "Deploy release candidates to a target environment with locking"
author: "flxbl-io"

branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  sfp-server-url:
    description: "URL to the SFP Server instance (e.g., https://your-org.flxbl.io)"
    required: true
  sfp-server-token:
    description: "Token for SFP Server authentication"
    required: true
  environment:
    description: "Target environment name to deploy to"
    required: true
  release-candidates:
    description: "Release candidate(s) in format 'domain:name' (e.g., 'core:RC-1' or 'core:RC-1,sales:RC-2')"
    required: true
  repository:
    description: "Repository name (format: owner/repo)"
    required: false
    default: ${{ github.repository }}
  devhub-alias:
    description: "Alias for the DevHub org (needed for unlocked package installations)"
    required: false
    default: "devhub"
  wait-time:
    description: "Wait time in minutes for package installation"
    required: false
    default: "120"
  tag:
    description: "Tag the release for identification in metrics"
    required: false
    default: ""
  exclude-packages:
    description: "Comma-separated list of packages to exclude from deployment (e.g., 'pkg-a,pkg-b')"
    required: false
    default: ""
  override-packages:
    description: "Comma-separated package version overrides (e.g., 'pkg-a=1.2.3,pkg-b=2.0.0')"
    required: false
    default: ""
  lock:
    description: "Lock environment before release (auto-unlock on completion)"
    required: false
    default: "true"
  lock-timeout:
    description: "Minutes to wait for lock acquisition (0 = wait indefinitely)"
    required: false
    default: "120"
  lock-duration:
    description: "Duration in minutes to hold the lock"
    required: false
    default: "120"
  dry-run:
    description: "Dry-run mode - compare and generate changelog without deploying"
    required: false
    default: "false"
  generate-changelog:
    description: "Generate changelog during release"
    required: false
    default: "true"
  update-issue:
    description: "Post changelog as issue/PR comment"
    required: false
    default: "true"
  issue-number:
    description: "Issue/PR number for comments (auto-detected if not provided)"
    required: false
    default: ""

outputs:
  deployment-status:
    description: "Status of the deployment (success/failed/dry-run)"
  ticket-id:
    description: "Lock ticket ID (if locking was enabled)"
  changelog-path:
    description: "Path to generated changelog markdown file"
  changelog-json-path:
    description: "Path to generated changelog JSON file"

runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/cleanup.js"
  post-if: "always()"
